### ISSUE TITLE
UnicodeDecodeError @ input_data.py

### ISSUE THREAD

**Issue by hajime9652** [Ruiqi-Hu/ARGA#5]
Traceback (most recent call last):
  File "ARGA/arga/run.py", line 18, in <module>
    runner.erun()
  File "ARGA/arga/link_prediction.py", line 24, in erun
    feas = format_data(self.data_name)
  File "ARGA/arga/constructor.py", line 42, in format_data
    adj, features, y_test, tx, ty, test_maks, true_labels = load_data(data_name)
  File "ARGA/arga/input_data.py", line 24, in load_data
    objects.append(pkl.load(open("data/ind.{}.{}".format(dataset, names[i]))))
  File ".pyenv/versions/3.5.1/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by hajime9652** [comment]
#1
